### ISSUE TITLE
.pyc files

### ISSUE THREAD

**Issue by niroberson** [bennames/AeroComBAT-Project#2]
You don't need to commit your  pyc files to the repo. You can add it to your .gitignore and rm *.pyc

**Comment by erock295** [comment]
That might have been an accident

On Monday, April 18, 2016, Nathan Roberson notifications@github.com wrote:

> You don't need to commit your pyc files to the repo. You can add it to
> your .gitignore and rm *.pyc
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/bennames/AeroComBAT-Project/issues/2

## 

Eric Plevy
Aerospace Engineering
Virginia Tech
Cell: (919)-259-9854

**Comment by bennames** [comment]
Thanks so much for the heads up. I'm still fairly new to git and clearly still getting the hang of it.
